openapi: 3.1.0
info:
  title: SimpliFi
  description: |-
    Welcome to SimpliFi platform! We are excited that you have taken the time to understand
    how the SimpliFi platform works, so let's start by going through some of the basic
    concepts of data types, API and Webhook structure and default parameters, etc.
  termsOfService: https://simplifipay.com/terms-and-conditions/
  contact:
    email: support@simplifipay.com
  version: 5.x.x
externalDocs:
  description: Find out more about SimpliFi
  url: https://simplifipay.com/
servers:
  - url: https://{env}-lb.simplifipay.com

tags:
  - name: auth
    description: |-
      The Auth API Group is designed to authorize you to start using the SimpliFi platform.
      This group has the Login endpoint that allows you to enter into our system. Moreover,
      the endpoint’s response provides you with the access token, which would be used in
      making further API calls.
  - name: card
    description: |-
      The Cards API Group is designed to manage all the activities related to the cards
      life cycle. Cards can either be issued in physical or virtual form, or both. Cards
      would inherit the default characteristics of the card program under which they have
      been issued, however, some of these can be changed at the card level. Cards could
      be issued only to a registered user within a card program.
  - name: webhook
    description: |-
      All the asynchronous API calls that are made using the endpoints published by the SimpliFi platform,
      return a webhook. The purpose of these webhooks is to inform the API user about the status of the
      endpoint that was initiated.

      The webhook structure remains the same in all the asynchronously running API calls with the only
      difference in `eventType` field and `eventPayload` object. These two fields are unique for every
      webhook response. `eventType` describes the event for which the webhook was generated and
      `eventPayload` describes the payload for that event.

paths:
  /v1/auth/login/{companyName}:
    post:
      tags:
        - auth
      security: []
      summary: Login to generate JWT token
      description: |-
        The Login endpoint allows you to login to the SimpliFi platform using the provided
        credentials. If you don't have the credentials already, you can request them through
        [this link](https://simplifipay.com/). The endpoint returns an access token to be
        used in making further API calls. Following are the properties of this endpoint.
      parameters:
        - $ref: '#/components/parameters/requestUuidParam'
        - name: companyName
          in: path
          description: |-
            This is an internal identifier of your company in the SimpliFi platform. We will
            generate the company name for you and share it. If you don't have it already,
            you can request it through [this link](https://simplifipay.com/).
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthRequestModel'
      responses:
        200:
          description: On successful operation JWT token is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseModel'

  /card/bulk/order:
    post:
      tags:
        - card
      summary: Add card bulk order
      description: |-
        This endpoint allows you to place a bulk order for gift cards in the specified currency. 
        The number of cards must be provided in the request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardBulkOrderRequestModel'
      responses:
        202:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardBulkOrderResponseModel'
        401:
          $ref: '#/components/responses/UnauthorizedError'

  /card/order/link:
    post:
      tags:
        - card
      summary: Create a Card Order Link
      description: |-
        This endpoint allows you to create a card order link by assigning one or more cards to a specific order.
        The link includes a load amount and relevant identifiers.
      requestBody:
        description: Card Order Link request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardOrderLinkRequest'
      responses:
        201:
          description: Card Order Link created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardOrderLinkResponse'
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /card/order/de-link:
    post:
      tags:
        - card
      summary: De-link a Card from Order
      description: |-
        This endpoint de-links one or more cards from a given card order, removing the association between them.
      requestBody:
        description: Card Order De-link request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardOrderDeLinkRequest'
      responses:
        201:
          description: Card Order de-linked successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardOrderDeLinkResponse'
        401:
          $ref: '#/components/responses/UnauthorizedError'

webhooks:
  bulkCardWebhook:
    post:
      tags:
        - webhook
      security: []
      summary: Bulk Card Order webhook
      description: A bulk order card is created in the SimpliFi system and a webhook is published.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardBulkOrderWebhookModel'
      responses:
        200:
          $ref: '#/components/responses/WebhookSuccessResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    EntityNotFoundError:
      description: Entity not found with the specified UUID
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
    WebhookSuccessResponse:
      description: Return a 200 status to indicate that the data was received successfully
  parameters:
    requestUuidParam:
      in: header
      name: requestUuid
      description: |-
        A unique id is required to be passed as part of the header whenever a SimpliFi API is called from your
        system. This would help us in debugging in case of a discrepancy in the expected behavior of the API.
      required: true
      schema:
        type: string
        example: '00d366f2-a6e9-4714-b172-02c4e58c29d8'

  schemas:
    ErrorModel:
      type: object
      properties:
        errorCode:
          type: integer
          description: A 5-7 digit number defining the error
          example: '99997'
        message:
          type: string
          description: A brief message defining the error
          example: 'General Error'
    AuthRequestModel:
      type: object
      properties:
        client_id:
          type: string
          description: |-
            The values of this enumeration identify your channel for calling the endpoint.
            Example: If you want to generate the access token to call subsequent APIs from
            your back-end system then use the value simplifi-api-client. Allowed values
            are: `simplifi-ios-client`, `simplifi-android-client`, and `simplifi-api-client`.
        client_secret:
          type: string
          description: |-
            This is a secret identification pattern assigned to you by the SimpliFi platform.
            For each allowed value of “client_id” there is a respective client secret value
            shared with you before the start of the integration. Pass the respective value here.
            If you don't have it already, you can request it through [this link](https://simplifipay.com/).
        grant_type:
          type: string
          description: |-
            You need to pass this value to log in through the Client Secret shared by SimpliFi.
            Allowed value is `client_credentials`. If you don't already have these credentials,
            you can request them through [this link](https://simplifipay.com/).
      required:
        - client_id
        - client_secret
        - grant_type
    AuthResponseModel:
      type: object
      properties:
        access_token:
          type: string
          description: |-
            This is the system-generated access token to be used for subsequent calls of the
            same session. It is to be sent as an authorization header along with the
            system-generated token type.
        expires_in:
          type: string
          description: |-
            This is the expiry date/time that defines the validity of the access token.
            Note (one needs to re-login before this expiration time).
        token_type:
          type: string
          description: |-
            This field contains the token type which is coupled with access token to form
            an authorization header. Accepted value is `bearer`.

    CardBulkOrderRequestModel:
      type: object
      properties:
        currency:
          type: string
          description: This field contains the currency in which the cards will be ordered.
          example: 'AED'
        numberOfCards:
          type: integer
          format: int64
          description: This field contains the total number of cards to be ordered.
          example: 1000
      required:
        - currency
        - numberOfCards
    CardBulkOrderResponseModel:
      type: object
      properties:
        uuid:
          type: string
          description: This field contains the unique identifier for the card bulk order.
          example: '36db6b79-f081-48db-9895-8faf45a53045'
        currency:
          type: string
          description: This field contains the currency of the ordered cards.
          example: 'AED'
        numberOfCards:
          type: integer
          format: int64
          description: This field contains the total number of cards ordered.
          example: 1000
        batchNumber:
          type: string
          description: This field contains the unique identifier of the bulk order batch.
          example: 'B-123'
      required:
        - uuid
        - currency
        - numberOfCards
        - batchNumber

    CardOrderLinkRequest:
      type: object
      properties:
        loadAmount:
          type: number
          format: decimal
          description: This field contains the the amount to be loaded on the cards.
          example: 50.75
        email:
          type: string
          description: This field contains the email of the user to whom the order is assigned.
          example: 'john.smith@simplifipay.com'
        orderIdentifier:
          type: string
          description: This field contains the identifier of the order.
          example: 'PO-123456'
        cardIdentifier:
          type: array
          description: This field contains the list of card identifiers to be included in the order.
          items:
            type: string
      required:
        - loadAmount
        - email
        - cardIdentifier
    CardOrderLinkResponse:
      type: object
      properties:
        orderStatus:
          type: string
          description: This field contains the the status of the order.
          example: 'LINKED'
          enum:
            - LINKED
            - DELINKED
            - REDEEMED
        loadAmount:
          type: number
          format: decimal
          description: This field contains the the amount loaded on the cards.
          example: 50.75
        email:
          type: string
          description: This field contains the email of the user to whom the order is assigned.
          example: 'john.smith@simplifipay.com'
        orderIdentifier:
          type: string
          description: This field contains the identifier of the order.
          example: 'PO-123456'
        cardIdentifier:
          type: array
          description: This field contains the list of card identifiers included in the order.
          items:
            type: string
      required:
        - orderStatus
        - loadAmount
        - email
        - cardIdentifier

    CardOrderDeLinkRequest:
      type: object
      properties:
        orderIdentifier:
          type: string
          description: This field contains the identifier of the order.
          example: 'PO-123456'
        cardIdentifier:
          type: array
          description: This field contains the list of card identifiers to be de-linked from the order.
          items:
            type: string
      required:
        - cardIdentifier

    CardOrderDeLinkResponse:
      type: object
      properties:
        orderStatus:
          type: string
          description: This field contains the status of the order after de-linking.
          example: 'DELINKED'
          enum:
            - LINKED
            - DELINKED
            - REDEEMED
        orderIdentifier:
          type: string
          description: This field contains the identifier of the order.
          example: 'PO-123456'
        cardIdentifier:
          type: array
          description: This field contains the list of card identifiers that were de-linked.
          items:
            type: string
      required:
        - orderStatus
        - cardIdentifier

    Webhook:
      type: object
      properties:
        uuid:
          type: string
          description: This field contains the unique uuid of the entity of the event.
          example: '929506e0-0b8f-4572-b492-5d3276c62bc5'
        requestUuid:
          type: string
          description: This field contains the unique uuid of the request that generated the event.
          example: '19c96ca8-cd68-4a4f-bb43-cd225502cbde'
        companyUuid:
          type: string
          description: This field contains the unique uuid of the company.
          example: 'a58cd30e-955a-4905-87e1-4d70a62624f5'
        requesterUuid:
          type: string
          description: This field contains the unique uuid of the user who generated the request.
          example: 'b0233bfb-10b4-4218-a807-2fef9c99f125'
        requestStatus:
          type: string
          description: This field contains the status of the event, whether it was a success or a failure
          example: 'SUCCESS'
          enum:
            - SUCCESS
            - FAILURE
        errorCode:
          type: string
          description: |-
            This field contains the error code when the `requestStatus` is a `FAILURE`.
            It is a 5-7 digit number defining the error.
        errorMessage:
          type: string
          description: |-
            This field contains the error message when the `requestStatus` is a `FAILURE`.
            It is a brief message defining the error.
        sourceErrorCode:
          type: string
          description: |-
            This field contains the error code, passed down from the processor,
            when the `requestStatus` is a `FAILURE`.
            It is a 5-7 digit number defining the error.
        sourceErrorMessage:
          type: string
          description: |-
            This field contains the error message, passed down from the processor,
            when the `requestStatus` is a `FAILURE`.
            It is a brief message defining the error.
    CardBulkOrderWebhookModel:
      allOf:
        - $ref: '#/components/schemas/Webhook'
        - type: object
          properties:
            eventType:
              type: string
              description: 'BULK_CARD_ISSUANCE'
              example: 'BULK_CARD_ISSUANCE'
            eventPayload:
              type: object
              properties:
                uuid:
                  type: string
                  description: This field contains a unique identifier of the bulk order.
                  example: '48a5599e-f628-412b-9c8e-ea387bde0a87'
                currency:
                  type: string
                  description: This field contains the currency of the ordered cards.
                  example: 'AED'
                numberOfCardsRequested:
                  type: integer
                  format: int64
                  description: This field contains the total number of cards ordered.
                  example: 1000
                numberOfCardsGenerated:
                  type: integer
                  format: int64
                  description: This field contains the total number of cards generated.
                  example: 1000
                batchNumber:
                  type: string
                  description: This field contains the unique identifier of the bulk order batch.
                  example: 'B-123'
                cards:
                  type: array
                  description: Details of the generated cards
                  items:
                    type: object
                    properties:
                      publicToken:
                        type: string
                        description: This field contains a unique identifier of the card to redeem card.

security:
  - bearerAuth: []
