openapi: 3.1.0
info:
  title: SimpliFi
  description: |-
    Welcome to SimpliFi platform! We are excited that you have taken the time to understand
    how the SimpliFi platform works, so let's start by going through some of the basic
    concepts of data types, API and Webhook structure and default parameters, etc.
  termsOfService: https://simplifipay.com/terms-and-conditions/
  contact:
    email: support@simplifipay.com
  version: 5.x.x
externalDocs:
  description: Find out more about SimpliFi
  url: https://simplifipay.com/
servers:
  - url: https://{env}-lb.simplifipay.com

tags:
  - name: auth
    description: |-
      The Auth API Group is designed to authorize you to start using the SimpliFi platform.
      This group has the Login endpoint that allows you to enter into our system. Moreover,
      the endpoint’s response provides you with the access token, which would be used in
      making further API calls.

paths:
  /v1/auth/login/{companyName}:
    post:
      tags:
        - auth
      security: []
      summary: Login to generate JWT token
      description: |-
        The Login endpoint allows you to login to the SimpliFi platform using the provided
        credentials. If you don't have the credentials already, you can request them through
        [this link](https://simplifipay.com/). The endpoint returns an access token to be
        used in making further API calls. Following are the properties of this endpoint.
      parameters:
        - $ref: '#/components/parameters/requestUuidParam'
        - name: companyName
          in: path
          description: |-
            This is an internal identifier of your company in the SimpliFi platform. We will
            generate the company name for you and share it. If you don't have it already,
            you can request it through [this link](https://simplifipay.com/).
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthRequestModel'
      responses:
        200:
          description: On successful operation JWT token is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseModel'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    EntityNotFoundError:
      description: Entity not found with the specified UUID
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
    WebhookSuccessResponse:
      description: Return a 200 status to indicate that the data was received successfully
  parameters:
    requestUuidParam:
      in: header
      name: requestUuid
      description: |-
        A unique id is required to be passed as part of the header whenever a SimpliFi API is called from your
        system. This would help us in debugging in case of a discrepancy in the expected behavior of the API.
      required: true
      schema:
        type: string
        example: '00d366f2-a6e9-4714-b172-02c4e58c29d8'
  schemas:
    ErrorModel:
      type: object
      properties:
        errorCode:
          type: integer
          description: A 5-7 digit number defining the error
          example: '99997'
        message:
          type: string
          description: A brief message defining the error
          example: 'General Error'
    AuthRequestModel:
      type: object
      properties:
        client_id:
          type: string
          description: |-
            The values of this enumeration identify your channel for calling the endpoint.
            Example: If you want to generate the access token to call subsequent APIs from
            your back-end system then use the value simplifi-api-client. Allowed values
            are: `simplifi-ios-client`, `simplifi-android-client`, and `simplifi-api-client`.
        client_secret:
          type: string
          description: |-
            This is a secret identification pattern assigned to you by the SimpliFi platform.
            For each allowed value of “client_id” there is a respective client secret value
            shared with you before the start of the integration. Pass the respective value here.
            If you don't have it already, you can request it through [this link](https://simplifipay.com/).
        grant_type:
          type: string
          description: |-
            You need to pass this value to log in through the Client Secret shared by SimpliFi.
            Allowed value is `client_credentials`. If you don't already have these credentials,
            you can request them through [this link](https://simplifipay.com/).
      required:
        - client_id
        - client_secret
        - grant_type
    AuthResponseModel:
      type: object
      properties:
        access_token:
          type: string
          description: |-
            This is the system-generated access token to be used for subsequent calls of the
            same session. It is to be sent as an authorization header along with the
            system-generated token type.
        expires_in:
          type: string
          description: |-
            This is the expiry date/time that defines the validity of the access token.
            Note (one needs to re-login before this expiration time).
        token_type:
          type: string
          description: |-
            This field contains the token type which is coupled with access token to form
            an authorization header. Accepted value is `bearer`.

security:
  - bearerAuth: []
